<?php

namespace AppBundle\Repository;

/**
 * AnonymousMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnonymousMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
